/**
 * scan-images.mjs
 * Scans public/images/products/{id}/ for each product and generates
 * src/data/product-images.ts with all found image paths.
 * Run automatically via "prebuild" and "predev" in package.json.
 */

import fs from 'fs'
import path from 'path'

const PRODUCTS_DIR = path.join(process.cwd(), 'public', 'images', 'products')
const OUTPUT_FILE = path.join(process.cwd(), 'src', 'data', 'product-images.ts')
const IMAGE_EXTS = /\.(jpg|jpeg|png|webp|gif|avif|mp4|mov)$/i

const result = {}

if (fs.existsSync(PRODUCTS_DIR)) {
  const entries = fs.readdirSync(PRODUCTS_DIR, { withFileTypes: true })
  const dirs = entries.filter((e) => e.isDirectory()).map((e) => e.name)

  for (const dir of dirs) {
    const dirPath = path.join(PRODUCTS_DIR, dir)
    const files = fs
      .readdirSync(dirPath)
      .filter((f) => IMAGE_EXTS.test(f))
      .sort()
      .map((f) => `/images/products/${dir}/${f}`)
    result[dir] = files
  }
}

const content = `// Auto-generated by scripts/scan-images.mjs — do not edit manually
// Re-generated on every "npm run build" and "npm run dev"
export const PRODUCT_IMAGES: Record<string, string[]> = ${JSON.stringify(result, null, 2)}
`

fs.writeFileSync(OUTPUT_FILE, content, 'utf8')
console.log('✓ product-images.ts generated:', Object.keys(result).length, 'products')
