/**
 * scan-images.mjs
 * Scans public/images/{about,gallery,products/*} and generates:
 *   - src/data/site-images.ts  (ABOUT_IMAGES, GALLERY_IMAGES, PRODUCT_IMAGES)
 *   - src/data/product-images.ts  (backward-compat export for useProductImages)
 *
 * NEXT_PUBLIC_BASE_PATH is set by actions/configure-pages@v5 before this runs.
 * Locally it's empty, so paths become /images/... which works with `next dev`.
 */

import fs from 'fs'
import path from 'path'

const BASE_PATH   = '/lumos-paola'
const PUBLIC_DIR  = path.join(process.cwd(), 'public', 'images')
const IMAGE_EXTS  = /\.(jpg|jpeg|png|webp|gif|avif|mp4|mov)$/i

function scanFolder(folder) {
  const dir = path.join(PUBLIC_DIR, folder)
  if (!fs.existsSync(dir)) return []
  return fs.readdirSync(dir)
    .filter((f) => IMAGE_EXTS.test(f))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }))
    .map((f) => `${BASE_PATH}/images/${folder}/${f}`)
}

function scanSubfolders(parent) {
  const dir = path.join(PUBLIC_DIR, parent)
  if (!fs.existsSync(dir)) return {}
  const result = {}
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      const imgs = scanFolder(`${parent}/${entry.name}`)
      result[entry.name] = imgs
    }
  }
  return result
}

const aboutImages    = scanFolder('about')
const galleryImages  = scanFolder('gallery')
const productImages  = scanSubfolders('products')

// site-images.ts — used by About.tsx and Gallery.tsx
fs.writeFileSync(
  path.join(process.cwd(), 'src', 'data', 'site-images.ts'),
  `// AUTO-GENERATED by scripts/scan-images.mjs — do not edit manually
// Re-generated on every "npm run build" and "npm run dev"

export const ABOUT_IMAGES: string[] = ${JSON.stringify(aboutImages, null, 2)}

export const GALLERY_IMAGES: string[] = ${JSON.stringify(galleryImages, null, 2)}

export const PRODUCT_IMAGES: Record<string, string[]> = ${JSON.stringify(productImages, null, 2)}
`,
  'utf8'
)

// product-images.ts — kept for backward-compat with useProductImages hook
fs.writeFileSync(
  path.join(process.cwd(), 'src', 'data', 'product-images.ts'),
  `// Auto-generated by scripts/scan-images.mjs — do not edit manually
// Re-generated on every "npm run build" and "npm run dev"
export const PRODUCT_IMAGES: Record<string, string[]> = ${JSON.stringify(productImages, null, 2)}
`,
  'utf8'
)

console.log(
  `✓ scan-images: about=${aboutImages.length} gallery=${galleryImages.length}` +
  ` products=${Object.keys(productImages).length} folders  BASE_PATH="${BASE_PATH}"`
)
