// Auto-generated by scripts/scan-images.mjs — do not edit manually
// Re-generated on every "npm run build" and "npm run dev"
export const PRODUCT_IMAGES: Record<string, string[]> = {
  "arreglo-14": [
    "/images/products/arreglo-14/arreglo-14.jpg"
  ],
  "arreglo-20": [
    "/images/products/arreglo-20/arreglo-20.jpg"
  ],
  "caja-love": [
    "/images/products/caja-love/caja-love.jpg"
  ],
  "caja-mom": [],
  "caja-personalizada": [
    "/images/products/caja-personalizada/caja-personalizada.jpg"
  ],
  "canasta": [
    "/images/products/canasta/canasta.jpg"
  ],
  "girasoles": [
    "/images/products/girasoles/girasoles.jpg"
  ],
  "lupita": [
    "/images/products/lupita/lupita.jpg"
  ],
  "margaritas": [],
  "peonias": [
    "/images/products/peonias/peonias.jpg"
  ],
  "recordatorios": [
    "/images/products/recordatorios/recordatorios.jpg"
  ],
  "rosas": [
    "/images/products/rosas/rosas-1.jpg",
    "/images/products/rosas/rosas-2.jpg",
    "/images/products/rosas/rosas-3.jpg",
    "/images/products/rosas/rosas.jpg"
  ]
}
