// AUTO-GENERATED by scripts/scan-images.mjs — do not edit manually
// Re-generated on every "npm run build" and "npm run dev"

export const ABOUT_IMAGES: string[] = [
  "/lumos-paola/images/about/galleri1.jpg",
  "/lumos-paola/images/about/galleri2.jpg",
  "/lumos-paola/images/about/galleri3.jpg"
]

export const GALLERY_IMAGES: string[] = [
  "/lumos-paola/images/gallery/CanastaDeVelasRosas.jpeg",
  "/lumos-paola/images/gallery/IloveyouVelasFlorales.jpeg",
  "/lumos-paola/images/gallery/MiniVelasPeonias.jpeg",
  "/lumos-paola/images/gallery/MOMcajadevelasflorales.jpeg",
  "/lumos-paola/images/gallery/RosasCajaRecuerdos.jpeg",
  "/lumos-paola/images/gallery/VelasaromaticasLUPITA.jpg",
  "/lumos-paola/images/gallery/VelasdeGirasoles.jpeg"
]

export const PRODUCT_IMAGES: Record<string, string[]> = {
  "arreglo-14": [
    "/lumos-paola/images/products/arreglo-14/arreglo-14.jpg"
  ],
  "arreglo-20": [
    "/lumos-paola/images/products/arreglo-20/arreglo-20.jpg"
  ],
  "caja-love": [
    "/lumos-paola/images/products/caja-love/caja-love.jpg"
  ],
  "caja-mom": [
    "/lumos-paola/images/products/caja-mom/mom.jpg"
  ],
  "caja-personalizada": [
    "/lumos-paola/images/products/caja-personalizada/caja-personalizada.jpg",
    "/lumos-paola/images/products/caja-personalizada/personalizado1.jpg"
  ],
  "canasta": [
    "/lumos-paola/images/products/canasta/canasta1.jpg",
    "/lumos-paola/images/products/canasta/canasta2.jpg"
  ],
  "girasoles": [
    "/lumos-paola/images/products/girasoles/girasoles1.jpg",
    "/lumos-paola/images/products/girasoles/girasoles2.jpg",
    "/lumos-paola/images/products/girasoles/girasoles3.jpg",
    "/lumos-paola/images/products/girasoles/girasoles4.jpg",
    "/lumos-paola/images/products/girasoles/girasoles5.jpg"
  ],
  "lupita": [
    "/lumos-paola/images/products/lupita/lupita.jpg",
    "/lumos-paola/images/products/lupita/lupita2.jpg",
    "/lumos-paola/images/products/lupita/lupita3.jpg",
    "/lumos-paola/images/products/lupita/lupita4.jpg",
    "/lumos-paola/images/products/lupita/lupita5.jpg",
    "/lumos-paola/images/products/lupita/lupita6.jpg",
    "/lumos-paola/images/products/lupita/lupita7.jpg",
    "/lumos-paola/images/products/lupita/lupita8.jpg",
    "/lumos-paola/images/products/lupita/lupita11.mp4"
  ],
  "margaritas": [
    "/lumos-paola/images/products/margaritas/margaritas.jpg",
    "/lumos-paola/images/products/margaritas/margaritas2.jpg",
    "/lumos-paola/images/products/margaritas/margaritas3.jpg",
    "/lumos-paola/images/products/margaritas/margaritas4.jpg",
    "/lumos-paola/images/products/margaritas/margaritas5.jpg",
    "/lumos-paola/images/products/margaritas/margaritas6.jpg",
    "/lumos-paola/images/products/margaritas/margaritas7.jpg",
    "/lumos-paola/images/products/margaritas/margaritas8.jpg",
    "/lumos-paola/images/products/margaritas/margaritas9.jpg"
  ],
  "peonias": [
    "/lumos-paola/images/products/peonias/peonias1.jpg",
    "/lumos-paola/images/products/peonias/peonias2.jpg",
    "/lumos-paola/images/products/peonias/peonias3.jpg"
  ],
  "recordatorios": [
    "/lumos-paola/images/products/recordatorios/recordatorios.jpg",
    "/lumos-paola/images/products/recordatorios/recuerdo2.jpg"
  ],
  "rosas": [
    "/lumos-paola/images/products/rosas/rosas-2.jpg",
    "/lumos-paola/images/products/rosas/rosas-3.jpg",
    "/lumos-paola/images/products/rosas/rosas.jpg"
  ]
}
